modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/MCTeamPotato"
license = "GPLv3"

[[mods]]
modId = "whousedrtpcommandmod"
#logoFile = "icon.png"
version = "${version}"
displayName = "Who Used RTP Command Mod"
authors = '''
MCTeamPotato
Awei
'''
description = '''
Who Used RTP Command!
'''
#logoFile = ""

[[dependencies.whousedrtpcommandmod]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.whousedrtpcommandmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
